### ISSUE TITLE
Enums shall be forbidden in Queen

### ISSUE THREAD

**Issue by amihaiemil** [jvmqueen/queen-antlr#21]
Enums are nothing more than sintactic sugar actually useful in very little cases (days of week, names of the months,...). Besides these few valid scenarios, enums only encourage quick, poor and meaningless abstractions. Let's remove them alltogether.

If the user really wants to have enums for the few valid scenarios, they can emulate the behaviour anyway.

**Comment by zoeself** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2022-12-10T09:00:31.435730``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@zoeself commands

**Comment by zoeself** [comment]
> @zoeself commands

Hi @amihaiemil! Here are the commands which I understand:

* ``Hello`` -- any comment addressed to the PM containing the word **"hello"**.

  Equivalent command: ``Hi``
* ``Status`` -- any comment addressed to the PM, containing the word **"status"**. The PM will respond with the Task's status, assignee, deadline etc.
* ``Resign`` -- a task's assignee can always resign from the task, if they cannot or simply do not want to solve it. The comment should be addressed to the PM and contain the word **"resign"**. Only the task's assignee can give this command.

  Equivalent commands: ``Refuse``, ``Quit``
* ``Deregister`` -- a task can be deregistered (taken out of scope) with a comment containing the word **"deregister"**. Only a Contributor with role ``PO`` or ``ARCH`` can give this command. When a task is deregistered, the task's assignee is automatically resigned.

  Equivalent command: ``Remove``
* ``Register`` -- an Issue or PR can be registered as a Task with a comment containing the word **"register"**. Any Contributor can give this command.

  Equivalent command: ``Add``

**Comment by amihaiemil** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@zoeself status

**Comment by zoeself** [comment]
> @zoeself status

@amihaiemil this ticket is not registered as a task, therefore I'm not working on it at the moment.

If you want me to take care of it, assign it to me or say "register".
