### ISSUE TITLE
Release 0.0.7 - Allow 'final' for implementations, fields and params

### ISSUE THREAD

**Issue by amihaiemil** [jvmqueen/queen-antlr#40]
#39

**Comment by zoeself** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.7`
